//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JCrud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_Address_Details
    {
        public long id { get; set; }
        public Nullable<long> Appartment_Number { get; set; }
        public string Street_Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zipcode { get; set; }
    
        public virtual Student_Details Student_Details { get; set; }
    }
}
