//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JCrud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_Details
    {
        public long id { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string Email { get; set; }
        public string DOB { get; set; }
        public string Phone_number { get; set; }
    
        public virtual Student_Address_Details Student_Address_Details { get; set; }
    }
}
